[project]
name = "test-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.68.0",
    "python-dotenv>=1.0.0",
    "fastapi>=0.117.1",
    "pytest>=8.4.2",
    "jupyter>=1.1.1",
]
